services:
  postgres:
    image: postgres:16-alpine
    container_name: nutech-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nutechdb
    networks:
      - nutech-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - DATABASE_URL_BUILD=postgresql://postgres:postgres@postgres:5432/nutechdb
    container_name: nutech-backend
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nutechdb
      - PORT=3010
      - NODE_ENV=production
      - JWT_SECRET=a28ad65ef495e93f19f75307869e6fc8
      - ALLOWED_ORIGINS="*"
    networks:
      - nutech-network

networks:
  nutech-network:
    driver: bridge

volumes:
  postgres_data: