services:
  postgres:
    image: postgres:16-alpine
    container_name: nutech-postgres
    restart: always
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    networks:
      - nutech-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - DATABASE_URL_BUILD=${DATABASE_URL}
    container_name: nutech-backend
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - PORT=${PORT}
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    networks:
      - nutech-network

networks:
  nutech-network:
    driver: bridge

volumes:
  postgres_data: